# Generated by Django 5.2 on 2025-05-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0002_alter_goal_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.IntegerField(default=10000),
        ),
    ]
