# Generated by Django 5.2 on 2025-05-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0009_rename_rateing_reviewandcomments_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='goal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalgoal',
            name='goal',
            field=models.IntegerField(),
        ),
    ]
