# Generated by Django 5.2 on 2025-05-06 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0011_remove_historicalgoal_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewandcomments',
            options={'ordering': ['-adding_at']},
        ),
    ]
