# Generated by Django 5.2 on 2025-05-06 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0014_goalhistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoalHistory',
            new_name='ProgressHistory',
        ),
    ]
