# Generated by Django 5.2 on 2025-05-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0015_rename_goalhistory_progresshistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='reviewandcomments',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
